# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# Uncomment and fill in the platforms you use:

# github: [your-username]
# patreon: your-patreon
# open_collective: your-collective
# ko_fi: your-ko-fi
# buy_me_a_coffee: your-bmc
# custom: ["https://your-link.com"]
